import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { createBuiltInDefaultPolicy, POLICY_CONFIG_SECTIONS } from "../../src/config/schema.ts";
import { DEFAULT_TUI_ARTIFACT_PATH, captureGuardMeTuiPanels } from "./helpers/tui-capture.mjs";

const DEFAULT_POLICY_RULE_COUNT = countPolicyRules(createBuiltInDefaultPolicy());

test("GuardMe TUI capture writes one sanitized panel artifact", { timeout: 60_000 }, async () => {
  const { artifactPath } = await captureGuardMeTuiPanels({ artifactPath: DEFAULT_TUI_ARTIFACT_PATH });
  const artifact = await readFile(artifactPath, "utf8");

  assert.match(artifact, /# GuardMe TUI Capture/);
  assert.match(artifact, /Captured Screen Index/);
  assert.match(artifact, /GuardMe Config/);
  assert.match(artifact, /Command - Help/);
  assert.match(artifact, /Setup - Select Local Defaults/);
  assert.match(artifact, /Create project policy with sensible defaults/);
  assert.match(artifact, /SETUP\s+2\/6/);
  assert.match(artifact, /Setup - Custom Defaults Confirm/);
  assert.match(artifact, /custom project policy • writes \.pi\/agent\/guardme\.yaml • choose defaults or blank/);
  assert.match(artifact, /CUSTOM POLICY START/);
  assert.match(artifact, /Start from sensible defaults\?/);
  assert.match(artifact, /Choose starting rules before adding custom entries\./);
  assert.match(artifact, new RegExp(`▶ Yes, keep defaults\\s+${DEFAULT_POLICY_RULE_COUNT} rules`));
  assert.match(artifact, /No, start blank\s+0 rules/);
  assert.match(artifact, /↑↓ choice\s+Enter select\s+Esc\/q quit/);
  assert.match(artifact, /Setup - Confirm Write/);
  assert.match(artifact, /CONFIRM WRITE/);
  assert.match(artifact, /Policy scope\s+project policy/);
  assert.match(artifact, /Starting rules\s+sensible defaults/);
  assert.match(artifact, /Write project policy • from sensible defaults/);
  assert.match(artifact, /Created GuardMe project policy/);
  assert.match(artifact, /Setup - Success Screen/);
  assert.match(artifact, /Setup - Success Screen[\s\S]*setup summary; run \/guardme for settings/);
  assert.match(artifact, /Setup - Success Screen[\s\S]*↑↓ row\s+Enter inspect\s+Tab pane/);
  assert.doesNotMatch(artifact, /Setup - Success Screen[\s\S]*Enter close[\s\S]*## Setup - Custom Rule Section/);
  assert.match(artifact, /Setup - Custom Rule Section/);
  assert.match(artifact, /Setup - Custom Rule Section[\s\S]*custom project policy • writes \.pi\/agent\/guardme\.yaml/);
  assert.match(artifact, /RULE SECTION/);
  assert.match(artifact, /1\/10 • project policy • allow matching path actions/);
  assert.match(artifact, /Setup - Custom Add Another Confirm/);
  assert.match(artifact, /CUSTOM RULES/);
  assert.match(artifact, /custom project policy • writes \.pi\/agent\/guardme\.yaml • add rules or confirm/);
  assert.match(artifact, /▶ Yes, add another rule\s+continue/);
  assert.match(artifact, /No, save policy\s+confirm/);
  assert.match(artifact, /1\/2 • Choose another rule section before saving\./);
  assert.match(artifact, /GENERAL/);
  assert.match(artifact, /## GENERAL\n\n[\s\S]*?↑↓ pane\s+Enter open\s+Tab rows/);
  assert.match(artifact, /## GENERAL\n\n[\s\S]*?│▶ General\s+│GENERAL/);
  assert.match(artifact, /## GENERAL\n\n[\s\S]*?│  Policies\s+│  GuardMe\s+active/);
  assert.doesNotMatch(artifact, /## GENERAL\n\n[\s\S]*?▶ GuardMe[\s\S]*?## POLICIES/);
  assert.match(artifact, /POLICIES/);
  assert.match(artifact, /loads ~\/\.pi\/agent\/guardme\.yaml → \.pi\/agent\/guardme\.yaml/);
  assert.match(artifact, /Global state\s+~\/\.pi\/agent\/guardme-state\.jsonl/);
  assert.match(artifact, /Project state\s+\.pi\/agent\/guardme-state\.jsonl/);
  assert.match(artifact, /RULES/);
  assert.match(artifact, /CATEGORY MATCHES\s+COUNT/);
  assert.match(artifact, /Protected policy files\s+3 matching rules/);
  assert.match(artifact, new RegExp(`Project policy file\\s+${DEFAULT_POLICY_RULE_COUNT} rules in file`));
  assert.match(artifact, /SOURCE \/ TOTAL\s+RULES/);
  assert.match(artifact, new RegExp(`Merged active policy\\s+${DEFAULT_POLICY_RULE_COUNT} active rules`));
  assert.match(artifact, /Category rows can overlap/);
  assert.doesNotMatch(artifact, /Custom project rules/);
  assert.doesNotMatch(artifact, /TOTAL:/);
  assert.match(artifact, /SETUP/);
  assert.doesNotMatch(artifact, /## DIAGNOSTICS(?:\n| -)/);
  assert.doesNotMatch(artifact, /│[▶ ] Diagnostics\s+│/);
  assert.match(artifact, /GENERAL - GuardMe Off/);
  assert.match(artifact, /GENERAL - Project Untrusted/);
  assert.match(artifact, /▶ Pi project trust\s+OFF/);
  assert.match(artifact, /Row 3\/5 • Trust OFF • Enter: trust project • after reload\/restart: project policy\/settings\/state can load/);
  assert.doesNotMatch(artifact, /## GENERAL - Project Untrusted[\s\S]*?│.*….*│[\s\S]*?## Search - Results/);
  assert.match(artifact, /Search - Results/);
  assert.match(artifact, /SEARCH TRUST/);
  assert.match(artifact, /Focus trust row; Pi trust controls project policy\/settings\/state/);
  assert.match(artifact, /Warning Detail Screen/);
  assert.match(artifact, /WARNINGS & DECISIONS\s+Line 1\/16/);
  assert.match(artifact, /Diagnostic Detail Screen/);
  assert.match(artifact, /DIAGNOSTIC DETAILS\s+Line 1\/5/);
  assert.match(artifact, /ERROR config\.invalidRoot/);
  assert.match(artifact, /Source\s+local \.pi\/agent\/guardme\.yaml/);
  assert.match(artifact, /Source line\s+12/);
  assert.match(artifact, /Action\s+Fix policy YAML or use Setup to recreate it\./);
  assert.match(artifact, /Confirm - GuardMe Off/);
  assert.match(artifact, /CONFIRM GUARDME OFF/);
  assert.match(artifact, /Confirm - Pi project trust/);
  assert.match(artifact, /CONFIRM PI PROJECT TRUST/);
  assert.match(artifact, /Pi project trust → OFF • GuardMe skips project policy\/settings\/state until trusted again/);
  assert.match(artifact, /GuardMe will skip project policy, settings, and state until trusted again/);
  assert.match(artifact, /Approval - Decision Modal/);
  assert.match(artifact, /APPROVAL REQUIRED/);
  assert.match(artifact, /GuardMe/);
  assert.match(artifact, /Pi project trust/);
  assert.match(artifact, /WARNINGS|Warning and Decision Details/);
  assert.match(artifact, /policy-missing-command/);
  assert.match(artifact, /deny-once/);
  assert.doesNotMatch(artifact, /\u001B|\u0007/);
});

function countPolicyRules(config) {
  return POLICY_CONFIG_SECTIONS.reduce((count, section) => count + config[section].length, 0);
}
